import { NextRequest, NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";
import nodemailer from "nodemailer";

// ── Types ──────────────────────────────────────────────────────────────────
interface ApplicationData {
  name: string;
  email: string;
  role: string;
  experience: string;
  skills: string;
}

// ── Gemini: Generate custom task ───────────────────────────────────────────
async function generateTask(data: ApplicationData): Promise<string> {
  const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);
  
  // Try models in order until one works
  const modelsToTry = ["gemini-2.0-flash", "gemini-2.0-flash-lite", "gemini-2.5-flash"];
  
  for (const modelName of modelsToTry) {
    try {
      const model = genAI.getGenerativeModel({ model: modelName });
      const prompt = `You are a technical hiring manager. A candidate has applied for a job.
Based on their profile, create a CUSTOM coding task that matches their exact level.

Candidate Profile:
- Name: ${data.name}
- Role Applied: ${data.role}
- Experience: ${data.experience}
- Skills: ${data.skills}

Rules:
- If experience is 0-2 years (Junior/Fresher): Give a SIMPLE task (e.g., build a basic component, simple CRUD, small function)
- If experience is 3-5 years (Mid-level): Give a MODERATE task (e.g., build a feature with state management, REST API)
- If experience is 5+ years (Senior/Lead): Give a HARD architectural task (e.g., design a scalable system, microservices, performance optimization)

Format your response EXACTLY like this:
---
TASK TITLE: [Short title]

DIFFICULTY: [Junior / Mid-level / Senior]

DESCRIPTION:
[2-3 sentences describing what to build]

REQUIREMENTS:
1. [Requirement 1]
2. [Requirement 2]
3. [Requirement 3]
4. [Requirement 4]

TIME LIMIT: [e.g., 2 hours / 4 hours / 1 day]

EVALUATION CRITERIA:
- [Criteria 1]
- [Criteria 2]
- [Criteria 3]
---

Make it specific to their skills (${data.skills}) and role (${data.role}).`;

      const result = await model.generateContent(prompt);
      return result.response.text();
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      // If quota or not found, try next model
      if (msg.includes("429") || msg.includes("404") || msg.includes("not found")) {
        console.log(`Model ${modelName} failed, trying next...`);
        continue;
      }
      throw err;
    }
  }
  
  throw new Error("All Gemini models failed. Please check your API key quota at aistudio.google.com");
}

// ── Nodemailer: Send email ─────────────────────────────────────────────────
async function sendEmail(data: ApplicationData, task: string): Promise<void> {
  const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: process.env.GMAIL_USER,
      pass: process.env.GMAIL_APP_PASSWORD,
    },
  });

  const htmlBody = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
      <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; border-radius: 12px 12px 0 0; text-align: center;">
        <h1 style="color: white; margin: 0; font-size: 24px;">🎯 Your Coding Task</h1>
        <p style="color: rgba(255,255,255,0.9); margin: 8px 0 0 0;">AI-Generated based on your profile</p>
      </div>
      
      <div style="background: #f8f9fa; padding: 25px; border-radius: 0 0 12px 12px; border: 1px solid #e9ecef;">
        <h2 style="color: #333; margin-top: 0;">Hello, ${data.name}! 👋</h2>
        <p style="color: #666;">Thank you for applying for the <strong>${data.role}</strong> position.</p>
        <p style="color: #666;">Based on your <strong>${data.experience}</strong> of experience and skills in <strong>${data.skills}</strong>, our AI has generated a custom task for you:</p>
        
        <div style="background: white; border-left: 4px solid #667eea; padding: 20px; border-radius: 8px; margin: 20px 0; white-space: pre-wrap; font-family: monospace; font-size: 14px; color: #333; line-height: 1.6;">
${task}
        </div>
        
        <p style="color: #888; font-size: 13px; margin-bottom: 0;">
          Good luck! Submit your solution within the given time limit.<br/>
          <em>This task was generated by AI based on your specific profile.</em>
        </p>
      </div>
    </div>
  `;

  await transporter.sendMail({
    from: `"AI Hiring System" <${process.env.GMAIL_USER}>`,
    to: data.email,
    subject: `🎯 Your Coding Task — ${data.role} Application`,
    html: htmlBody,
    text: `Hello ${data.name},\n\nYour custom coding task:\n\n${task}\n\nGood luck!`,
  });
}

// ── Main API Handler ───────────────────────────────────────────────────────
export async function POST(req: NextRequest) {
  try {
    const body: ApplicationData = await req.json();

    // Validate required fields
    const { name, email, role, experience, skills } = body;
    if (!name || !email || !role || !experience || !skills) {
      return NextResponse.json(
        { error: "All fields are required" },
        { status: 400 }
      );
    }

    // Check env variables
    if (!process.env.GEMINI_API_KEY || !process.env.GMAIL_USER || !process.env.GMAIL_APP_PASSWORD) {
      return NextResponse.json(
        { error: "Server configuration missing. Check environment variables." },
        { status: 500 }
      );
    }

    console.log(`📋 Processing application from: ${name} (${email}) for ${role}`);

    // Step 1: Generate task with Gemini AI
    console.log("🤖 Calling Gemini AI...");
    const task = await generateTask(body);
    console.log("✅ Task generated successfully");

    // Step 2: Send email
    console.log("📧 Sending email...");
    await sendEmail(body, task);
    console.log("✅ Email sent successfully");

    return NextResponse.json({
      success: true,
      message: "Task generated and emailed successfully",
    });

  } catch (error: unknown) {
    console.error("❌ Error:", error);
    const errorMessage = error instanceof Error ? error.message : "Internal server error";
    return NextResponse.json(
      { error: errorMessage },
      { status: 500 }
    );
  }
}
