import { NextRequest, NextResponse } from "next/server";
import nodemailer from "nodemailer";
import PDFDocument from "pdfkit";
import { store } from "@/lib/store";
import { openRouterChat } from "@/lib/openrouter";
import pdfParseLib from "pdf-parse";
import mammoth from "mammoth";

// ── Types ──────────────────────────────────────────────────────────────────
interface ApplicationData {
  name: string;
  email: string;
  role: string;
  experience: string;
  skills: string;
  resumeBuffer?: Buffer;
  resumeFilename?: string;
  resumeMimeType?: string;
  resumeText?: string; // extracted plain text from CV
}

interface GeneratedTask {
  title: string;
  scenario: string;
  requirements: string[];
  deliverables: string[];
  evaluation_criteria: string[];
  deadline_days: number;
  difficulty: string;
}

// ── CV text extraction ─────────────────────────────────────────────────────
async function extractResumeText(buffer: Buffer, mimeType: string): Promise<string> {
  try {
    if (mimeType === "application/pdf") {
      // pdf-parse v1 simple API: pdfParse(buffer)
      const result = await pdfParseLib(buffer);
      return result.text.slice(0, 4000);
    }
    if (
      mimeType === "application/msword" ||
      mimeType === "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    ) {
      const result = await mammoth.extractRawText({ buffer });
      return result.value.slice(0, 4000);
    }
  } catch (err) {
    console.warn("⚠️ CV text extraction failed:", err);
  }
  return "";
}

// ── GitHub: Create a fresh repo for the candidate ─────────────────────────
async function createCandidateRepo(
  candidateName: string,
  task: GeneratedTask
): Promise<{ repoUrl: string; repoOwner: string; repoName: string }> {
  const token = process.env.GITHUB_TOKEN;
  if (!token) throw new Error("GITHUB_TOKEN not set");

  const slug = `${candidateName}-${task.title}`
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);

  // 1. Create repo
  const createRes = await fetch("https://api.github.com/user/repos", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
      "X-GitHub-Api-Version": "2022-11-28",
    },
    body: JSON.stringify({
      name: slug,
      description: `Technical assignment repository for ${candidateName} (${task.difficulty})`,
      private: false,
      auto_init: true,
    }),
  });

  if (!createRes.ok) {
    const err = await createRes.json();
    throw new Error(`GitHub repo creation failed: ${err.message ?? createRes.status}`);
  }

  const repo = await createRes.json();
  const repoOwner: string = repo.owner.login;
  const repoName: string  = repo.name;

  // 2. Push TASK.md with full task details
  const taskMdContent = [
    `# ${task.title}`,
    ``,
    `**Difficulty:** ${task.difficulty}  `,
    `**Deadline:** ${task.deadline_days} days`,
    ``,
    `## Scenario`,
    ``,
    task.scenario,
    ``,
    `## Requirements`,
    ``,
    ...task.requirements.map((r, i) => `${i + 1}. ${r}`),
    ``,
    `## Deliverables`,
    ``,
    ...task.deliverables.map((d) => `- ${d}`),
    ``,
    `## Evaluation Criteria`,
    ``,
    ...task.evaluation_criteria.map((c) => `- ${c}`),
    ``,
    `---`,
    `*Generated by Sensussoft Hiring System*`,
  ].join("\n");

  // Wait briefly for GitHub to initialise the repo
  await new Promise((r) => setTimeout(r, 1500));

  await fetch(
    `https://api.github.com/repos/${repoOwner}/${repoName}/contents/TASK.md`,
    {
      method: "PUT",
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: "application/vnd.github+json",
        "Content-Type": "application/json",
        "X-GitHub-Api-Version": "2022-11-28",
      },
      body: JSON.stringify({
        message: "Add TASK.md",
        content: Buffer.from(taskMdContent).toString("base64"),
      }),
    }
  );

  return { repoUrl: repo.html_url as string, repoOwner, repoName };
}

// ── OpenRouter: Validate candidate before generating task ─────────────────
interface ValidationResult {
  valid: true;
  category: string;
  detected_seniority: string;
  summary: string;
}
interface ValidationFailed {
  valid: false;
  error: string;
}
type ValidationResponse = ValidationResult | ValidationFailed;

async function validateCandidate(data: ApplicationData): Promise<ValidationResponse> {
  const cvBlock = data.resumeText
    ? `\nCandidate CV (extracted):\n"""\n${data.resumeText.slice(0, 2000)}\n"""`
    : "";

  const systemPrompt = `You are a candidate validation system for Sensussoft hiring platform.
Your job is to check if a candidate application is genuine or spam/fake.

ACCEPT if the candidate:
- Has a role that is clearly IT/software related (even with minor typos like "devloper", "enginer", "desiner")
- Has skills that are real technologies or tools (React, Node.js, Python, Figma, AWS, etc.)
- Has a name that looks like a real person (at least 3 characters)
- Has a valid email format

REJECT only if the candidate is clearly fake/spam:
- Role is complete gibberish (e.g. "asdfgh", "xyz123", "aaabbb", random keyboard mashing)
- Skills are all gibberish (e.g. "fdse asd qwerty" with no real tech words at all)
- Name is clearly fake (e.g. single character, random symbols)

IMPORTANT:
- Be LENIENT with typos. "full stack devloper", "reactjs", "node js", "ui ux desiner" are all VALID.
- A mix of real and slightly misspelled tech skills is VALID.
- When in doubt, ACCEPT the candidate. It is better to accept a borderline case than reject a real candidate.
- Only reject obvious spam/gibberish.

If INVALID — return ONLY:
{"valid": false, "error": "Invalid professional role or fake candidate data detected"}

If VALID — return ONLY:
{"valid": true, "category": "development|design|qa|devops|product", "detected_seniority": "junior|mid|senior", "summary": "short candidate summary"}

Return ONLY raw JSON, no markdown, no explanation.`;

  const userPrompt = `Validate this candidate:
- Name: ${data.name}
- Email: ${data.email}
- Role applied: ${data.role}
- Experience: ${data.experience}
- Skills: ${data.skills}
${cvBlock}

Return ONLY valid JSON, no markdown, no explanation.`;

  try {
    let text = await openRouterChat({
      model: "meta-llama/llama-3.3-70b-instruct",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user",   content: userPrompt },
      ],
      temperature: 0.1,
      max_tokens: 200,
    });

    text = text.replace(/```json|```/g, "").trim();
    const result: ValidationResponse = JSON.parse(text);
    return result;
  } catch (err) {
    // If validation itself fails, log and allow through (fail-open)
    console.warn("⚠️ Validation AI call failed, allowing through:", err);
    return { valid: true, category: "development", detected_seniority: "mid", summary: "Validation skipped" };
  }
}

// ── OpenRouter: Generate custom task as JSON ──────────────────────────────

// Detect role category so the AI picks the right deliverable type
function detectRoleCategory(role: string): string {
  const r = role.toLowerCase();
  if (/design|ui|ux|visual|graphic|figma|product design/.test(r)) return "design";
  if (/qa|tester|sdet|quality|automation|test engineer/.test(r))   return "qa";
  if (/devops|sre|platform|cloud|infra|infrastructure|cicd|ci\/cd/.test(r)) return "devops";
  if (/product manager|pm\b|business analyst|ba\b|roadmap/.test(r)) return "product";
  // default: development
  return "development";
}

const CATEGORY_DELIVERABLE: Record<string, string> = {
  design:      "A Figma file (share link) or a PDF of your mockups/wireframes",
  qa:          "A test plan document + at least one automation script (any framework)",
  devops:      "A GitHub repo containing CI/CD config or Infrastructure-as-Code files",
  product:     "A PRD (Product Requirements Document) or a prioritised roadmap document",
  development: "A GitHub repository link with working code",
};

const CATEGORY_TASK_TYPE: Record<string, string> = {
  design:      "UI/UX design challenge",
  qa:          "QA / test engineering challenge",
  devops:      "DevOps / infrastructure challenge",
  product:     "Product management challenge",
  development: "software development challenge",
};

async function generateTask(data: ApplicationData): Promise<GeneratedTask> {
  // Parse experience years from string like "1-2 years", "7+ years"
  const expStr = data.experience.toLowerCase();
  let expYears = 0;
  if (expStr.includes("7+") || expStr.includes("lead") || expStr.includes("architect")) expYears = 7;
  else if (expStr.includes("5") || expStr.includes("senior")) expYears = 5;
  else if (expStr.includes("3")) expYears = 3;
  else if (expStr.includes("1")) expYears = 1;

  const category   = detectRoleCategory(data.role);
  const deliverable = CATEGORY_DELIVERABLE[category];
  const taskType    = CATEGORY_TASK_TYPE[category];

  // Build CV context block if we extracted text from the resume
  const cvContext = data.resumeText
    ? `\nCandidate CV / Resume (extracted text):\n"""\n${data.resumeText}\n"""\nUse the CV to personalise the task — reference the candidate's actual projects, technologies, and experience level where relevant.\n`
    : "";

  const prompt = `You are a hiring manager at Sensussoft creating a take-home assessment.
Generate a practical ${taskType} for the candidate below.
${cvContext}
Candidate:
- Name: ${data.name}
- Role applied: ${data.role}
- Experience: ${data.experience} (approx ${expYears} years)
- Skills: ${data.skills}

Role category: ${category}
Required deliverable: ${deliverable}

Difficulty rules:
- Junior (0-2y): focused, well-scoped task, ~3 hours of work.
- Mid-level (3-5y): broader task with multiple components, ~6 hours.
- Senior (6+y): architecture or strategy problem + implementation, ~8 hours.

Important:
- The task MUST match the role category (${category}). Do NOT generate a coding task for a design or PM role.
- Tailor requirements to the candidate's actual skills and experience from their CV if provided.
- The deliverable MUST be: ${deliverable}
- Deadline: 3 days.
- Include exactly 4 evaluation criteria relevant to the role category.

Return ONLY valid JSON with these exact keys:
{
  "title": "string",
  "difficulty": "Junior | Mid-level | Senior",
  "scenario": "string (2-3 sentences)",
  "requirements": ["string", "string", "string", "string"],
  "deliverables": ["${deliverable}"],
  "evaluation_criteria": ["string", "string", "string", "string"],
  "deadline_days": number
}

No markdown, no code fences, just raw JSON.`;

  // OpenRouter model fallback chain
  const modelsToTry = [
    "meta-llama/llama-3.3-70b-instruct",
    "meta-llama/llama-3.1-8b-instruct",
    "google/gemma-2-9b-it",
  ];

  for (const modelName of modelsToTry) {
    try {
      let text = await openRouterChat({
        model: modelName,
        messages: [{ role: "user", content: prompt }],
        temperature: 0.7,
        max_tokens: 1024,
      });

      // Strip markdown code fences if model wraps JSON
      text = text.replace(/```json|```/g, "").trim();

      const parsed: GeneratedTask = JSON.parse(text);
      console.log(`✅ Task generated with model: ${modelName} (category: ${category})`);
      return parsed;
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      console.log(`⚠️ Model ${modelName} failed: ${msg}, trying next...`);
    }
  }

  throw new Error("All AI models failed. Please check your OPENROUTER_API_KEY.");
}

// ── PDFKit: Generate PDF buffer ────────────────────────────────────────────
async function generatePDF(data: ApplicationData, task: GeneratedTask): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 0, size: "A4" });
    const chunks: Buffer[] = [];
    const W = 595.28; // A4 width in points
    const MARGIN = 48;
    const CONTENT_W = W - MARGIN * 2;

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // ── Helpers ──────────────────────────────────────────────────────────
    const diffColor = task.difficulty === "Senior"   ? "#dc2626" :
                      task.difficulty === "Mid-level" ? "#d97706" : "#16a34a";

    const diffBg    = task.difficulty === "Senior"   ? "#fef2f2" :
                      task.difficulty === "Mid-level" ? "#fffbeb" : "#f0fdf4";

    // Draw a filled rounded rectangle (PDFKit helper)
    function filledRoundRect(x: number, y: number, w: number, h: number, r: number, color: string) {
      doc.roundedRect(x, y, w, h, r).fill(color);
    }

    // Section heading with left accent bar
    function sectionHeading(label: string, y: number): number {
      // accent bar
      doc.rect(MARGIN, y, 3, 18).fill("#db2777");
      doc.fillColor("#111827").fontSize(12).font("Helvetica-Bold")
        .text(label, MARGIN + 10, y + 2, { lineBreak: false });
      return y + 18 + 10; // return next Y
    }

    // ── HEADER BAND ───────────────────────────────────────────────────────
    doc.rect(0, 0, W, 110).fill("#0f172a");

    // Brand name
    doc.fillColor("#f8fafc").fontSize(20).font("Helvetica-Bold")
      .text("Sensussoft", MARGIN, 28, { lineBreak: false });

    // Subtitle
    doc.fillColor("#94a3b8").fontSize(9).font("Helvetica")
      .text("AI-Generated Candidate Assessment", MARGIN, 54, { lineBreak: false });

    // Difficulty pill (top-right)
    const pillW = 90;
    filledRoundRect(W - MARGIN - pillW, 30, pillW, 22, 11, diffBg);
    doc.fillColor(diffColor).fontSize(9).font("Helvetica-Bold")
      .text(task.difficulty.toUpperCase(), W - MARGIN - pillW, 37,
        { width: pillW, align: "center", lineBreak: false });

    // Thin accent line at bottom of header
    doc.rect(0, 110, W, 3).fill("#db2777");

    // ── TASK TITLE BLOCK ──────────────────────────────────────────────────
    let curY = 130;

    doc.fillColor("#111827").fontSize(17).font("Helvetica-Bold")
      .text(task.title, MARGIN, curY, { width: CONTENT_W, lineBreak: true });

    curY = doc.y + 6;

    // Scenario text
    doc.fillColor("#4b5563").fontSize(10).font("Helvetica")
      .text(task.scenario, MARGIN, curY, { width: CONTENT_W, lineGap: 3 });

    curY = doc.y + 18;

    // ── CANDIDATE INFO CARD ───────────────────────────────────────────────
    const cardH = 72;
    filledRoundRect(MARGIN, curY, CONTENT_W, cardH, 8, "#f8fafc");
    doc.rect(MARGIN, curY, CONTENT_W, cardH).stroke("#e2e8f0");

    const col1 = MARGIN + 16;
    const col2 = MARGIN + CONTENT_W / 2 + 8;
    const rowGap = 18;
    const labelY1 = curY + 14;
    const labelY2 = curY + 14 + rowGap;
    const labelY3 = curY + 14 + rowGap * 2;

    // Labels
    doc.fillColor("#9ca3af").fontSize(8).font("Helvetica-Bold");
    doc.text("NAME",       col1,  labelY1, { lineBreak: false });
    doc.text("EMAIL",      col2,  labelY1, { lineBreak: false });
    doc.text("ROLE",       col1,  labelY2, { lineBreak: false });
    doc.text("EXPERIENCE", col2,  labelY2, { lineBreak: false });
    doc.text("SKILLS",     col1,  labelY3, { lineBreak: false });

    // Values
    doc.fillColor("#111827").fontSize(9).font("Helvetica");
    doc.text(data.name,       col1,  labelY1 + 9, { lineBreak: false });
    doc.text(data.email,      col2,  labelY1 + 9, { lineBreak: false });
    doc.text(data.role,       col1,  labelY2 + 9, { lineBreak: false });
    doc.text(data.experience, col2,  labelY2 + 9, { lineBreak: false });
    doc.text(data.skills,     col1,  labelY3 + 9, { width: CONTENT_W - 20, lineBreak: false });

    curY += cardH + 24;

    // ── REQUIREMENTS ─────────────────────────────────────────────────────
    curY = sectionHeading("Requirements", curY);

    task.requirements.forEach((req, i) => {
      // Number circle
      filledRoundRect(MARGIN, curY + 1, 18, 18, 9, "#fce7f3");
      doc.fillColor("#db2777").fontSize(8).font("Helvetica-Bold")
        .text(`${i + 1}`, MARGIN, curY + 5, { width: 18, align: "center", lineBreak: false });

      doc.fillColor("#374151").fontSize(10).font("Helvetica")
        .text(req, MARGIN + 24, curY + 3, { width: CONTENT_W - 24, lineGap: 2 });

      curY = doc.y + 8;
    });

    curY += 6;

    // ── DELIVERABLES ──────────────────────────────────────────────────────
    curY = sectionHeading("Deliverables", curY);

    task.deliverables.forEach((d) => {
      doc.fillColor("#db2777").fontSize(12).font("Helvetica-Bold")
        .text("›", MARGIN + 2, curY + 1, { lineBreak: false });
      doc.fillColor("#374151").fontSize(10).font("Helvetica")
        .text(d, MARGIN + 18, curY + 3, { width: CONTENT_W - 18, lineGap: 2 });
      curY = doc.y + 8;
    });

    curY += 6;

    // ── EVALUATION CRITERIA ───────────────────────────────────────────────
    curY = sectionHeading("Evaluation Criteria", curY);

    task.evaluation_criteria.forEach((c) => {
      // Checkmark circle
      filledRoundRect(MARGIN, curY + 1, 18, 18, 9, "#dcfce7");
      doc.fillColor("#16a34a").fontSize(9).font("Helvetica-Bold")
        .text("✓", MARGIN, curY + 4, { width: 18, align: "center", lineBreak: false });

      doc.fillColor("#374151").fontSize(10).font("Helvetica")
        .text(c, MARGIN + 24, curY + 3, { width: CONTENT_W - 24, lineGap: 2 });

      curY = doc.y + 8;
    });

    curY += 10;

    // ── DEADLINE BANNER ───────────────────────────────────────────────────
    filledRoundRect(MARGIN, curY, CONTENT_W, 38, 8, "#fdf2f8");
    doc.rect(MARGIN, curY, CONTENT_W, 38).stroke("#fce7f3");
    // Clock icon substitute
    doc.fillColor("#db2777").fontSize(14).font("Helvetica-Bold")
      .text("⏰", MARGIN + 14, curY + 10, { lineBreak: false });
    doc.fillColor("#831843").fontSize(10).font("Helvetica-Bold")
      .text(`Deadline: ${task.deadline_days} days from receipt of this email`,
        MARGIN + 36, curY + 13, { lineBreak: false });

    // ── FOOTER ────────────────────────────────────────────────────────────
    const footerY = 841.89 - 36; // A4 height - 36
    doc.rect(0, footerY, W, 36).fill("#0f172a");
    doc.fillColor("#64748b").fontSize(8).font("Helvetica")
      .text(
        `Generated by Sensussoft Hiring System  ·  ${new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" })}`,
        MARGIN, footerY + 13,
        { width: CONTENT_W, align: "center", lineBreak: false }
      );

    doc.end();
  });
}


function renderEmail(data: ApplicationData, task: GeneratedTask, repoUrl: string): string {
  const year = new Date().getFullYear();

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <title>Your Task — Sensussoft</title>
</head>
<body style="margin:0;padding:0;background:#f4f4f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,sans-serif;">

  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f4f5;padding:48px 16px;">
    <tr><td align="center">
      <table width="560" cellpadding="0" cellspacing="0" style="max-width:560px;width:100%;">

        <!-- Logo -->
        <tr>
          <td style="padding-bottom:28px;text-align:center;">
            <table cellpadding="0" cellspacing="0" align="center">
              <tr>
                <td style="background:#db2777;width:36px;height:36px;border-radius:10px;text-align:center;vertical-align:middle;">
                  <span style="color:white;font-weight:800;font-size:18px;line-height:36px;display:block;">S</span>
                </td>
                <td style="padding-left:10px;font-size:20px;font-weight:700;color:#18181b;vertical-align:middle;letter-spacing:-0.3px;">
                  Sensussoft
                </td>
              </tr>
            </table>
          </td>
        </tr>

        <!-- Card -->
        <tr>
          <td style="background:#ffffff;border-radius:20px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06);">

            <!-- Top accent bar -->
            <table width="100%" cellpadding="0" cellspacing="0">
              <tr>
                <td style="background:#db2777;height:5px;font-size:0;line-height:0;">&nbsp;</td>
              </tr>
            </table>

            <!-- Content -->
            <table width="100%" cellpadding="0" cellspacing="0">
              <tr>
                <td style="padding:40px 44px 36px;">

                  <!-- Greeting -->
                  <h1 style="margin:0 0 8px 0;font-size:22px;font-weight:800;color:#18181b;line-height:1.3;">
                    Hi ${data.name}, your task is attached! 👋
                  </h1>
                  <p style="margin:0 0 28px 0;font-size:15px;color:#71717a;line-height:1.6;">
                    Thank you for applying to <strong style="color:#18181b;">Sensussoft</strong> for the
                    <strong style="color:#db2777;">${data.role}</strong> position.
                  </p>

                  <!-- Divider -->
                  <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:28px;">
                    <tr><td style="height:1px;background:#f4f4f5;font-size:0;">&nbsp;</td></tr>
                  </table>

                  <!-- PDF notice box -->
                  <table width="100%" cellpadding="0" cellspacing="0" style="background:#fdf2f8;border-radius:12px;border:1px solid #fce7f3;margin-bottom:28px;">
                    <tr>
                      <td style="padding:22px 24px;">
                        <table cellpadding="0" cellspacing="0">
                          <tr>
                            <td style="vertical-align:top;padding-right:14px;font-size:24px;line-height:1;">📎</td>
                            <td>
                              <p style="margin:0 0 4px 0;font-size:15px;font-weight:700;color:#18181b;">
                                Your coding task is in the PDF
                              </p>
                              <p style="margin:0;font-size:13px;color:#71717a;line-height:1.6;">
                                We've attached a personalised PDF with your full task details — requirements, deliverables, and evaluation criteria.
                                Please open the attachment to get started.
                              </p>
                            </td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                  </table>

                  <!-- Steps -->
                  <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:28px;">
                    <tr>
                      <td style="padding-bottom:14px;">
                        <span style="font-size:12px;font-weight:700;color:#a1a1aa;text-transform:uppercase;letter-spacing:0.8px;">What to do next</span>
                      </td>
                    </tr>
                    <tr>
                      <td>
                        <table cellpadding="0" cellspacing="0" width="100%">
                          <tr>
                            <td style="padding:10px 0;border-bottom:1px solid #f4f4f5;">
                              <table cellpadding="0" cellspacing="0">
                                <tr>
                                  <td style="width:28px;height:28px;background:#fdf2f8;border-radius:50%;text-align:center;vertical-align:middle;font-size:13px;font-weight:700;color:#db2777;">1</td>
                                  <td style="padding-left:12px;font-size:14px;color:#3f3f46;">Open the attached PDF and read your task carefully.</td>
                                </tr>
                              </table>
                            </td>
                          </tr>
                          <tr>
                            <td style="padding:10px 0;border-bottom:1px solid #f4f4f5;">
                              <table cellpadding="0" cellspacing="0">
                                <tr>
                                  <td style="width:28px;height:28px;background:#fdf2f8;border-radius:50%;text-align:center;vertical-align:middle;font-size:13px;font-weight:700;color:#db2777;">2</td>
                                  <td style="padding-left:12px;font-size:14px;color:#3f3f46;">Complete the task and push your code to the repository.</td>
                                </tr>
                              </table>
                            </td>
                          </tr>
                          <tr>
                            <td style="padding:10px 0;">
                              <table cellpadding="0" cellspacing="0">
                                <tr>
                                  <td style="width:28px;height:28px;background:#fdf2f8;border-radius:50%;text-align:center;vertical-align:middle;font-size:13px;font-weight:700;color:#db2777;">3</td>
                                  <td style="padding-left:12px;font-size:14px;color:#3f3f46;">Reply to this email with your GitHub repo link within <strong style="color:#db2777;">${task.deadline_days} days</strong>.</td>
                                </tr>
                              </table>
                            </td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                  </table>

                  <!-- Two buttons -->
                  <table cellpadding="0" cellspacing="0" style="margin-bottom:32px;">
                    <tr>
                      <td>
                        <a href="${repoUrl}"
                           style="display:inline-block;padding:12px 20px;background:#db2777;color:white;text-decoration:none;font-size:14px;font-weight:600;border-radius:10px;">
                          View Starter Repository →
                        </a>
                      </td>
                    </tr>
                  </table>

                  <!-- Divider -->
                  <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:24px;">
                    <tr><td style="height:1px;background:#f4f4f5;font-size:0;">&nbsp;</td></tr>
                  </table>

                  <!-- Sign off -->
                  <p style="margin:0;font-size:14px;color:#71717a;line-height:1.7;">
                    Good luck — we're excited to see what you build!<br/>
                    <strong style="color:#18181b;">Sensussoft Hiring Team</strong>
                  </p>

                </td>
              </tr>
            </table>

          </td>
        </tr>

        <!-- Footer -->
        <tr>
          <td style="padding:28px 0 0;text-align:center;">
            <p style="margin:0 0 4px;font-size:12px;color:#a1a1aa;">© ${year} Sensussoft. All rights reserved.</p>
            <p style="margin:0;font-size:12px;color:#d4d4d8;">This task was AI-generated based on your application profile.</p>
          </td>
        </tr>

      </table>
    </td></tr>
  </table>

</body>
</html>`;
}

// ── Nodemailer: Send email with PDF attachment ─────────────────────────────
async function sendEmail(data: ApplicationData, task: GeneratedTask, repoUrl: string): Promise<void> {
  const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: process.env.GMAIL_USER,
      pass: process.env.GMAIL_APP_PASSWORD!.replace(/\s/g, ""),
    },
  });

  // Generate PDF
  console.log("📄 Generating PDF...");
  const pdfBuffer = await generatePDF(data, task);
  const pdfFilename = `Sensussoft_Task_${data.name.replace(/\s+/g, "_")}.pdf`;

  // Build attachments — always include the generated task PDF
  const attachments: { filename: string; content: Buffer; contentType: string }[] = [
    {
      filename: pdfFilename,
      content: pdfBuffer,
      contentType: "application/pdf",
    },
  ];

  // Resume is used only for AI text extraction — not attached to the email

  await transporter.sendMail({
    from: `"Sensussoft Careers" <${process.env.GMAIL_USER}>`,
    to: data.email,
    subject: `Sensussoft — Practical Task for ${data.role}`,
    html: renderEmail(data, task, repoUrl),
    text: `Hi ${data.name},\n\nTask: ${task.title}\n\nScenario: ${task.scenario}\n\nRequirements:\n${task.requirements.join("\n")}\n\nDeadline: ${task.deadline_days} days\n\nGood luck!\nSensussoft Hiring Team`,
    attachments,
  });
}

// ── Main API Handler ───────────────────────────────────────────────────────
export async function POST(req: NextRequest) {
  try {
    // Parse multipart/form-data (resume upload) or fall back to JSON
    let name: string, email: string, role: string, experience: string, skills: string;
    let resumeBuffer: Buffer | undefined;
    let resumeFilename: string | undefined;
    let resumeMimeType: string | undefined;

    const contentType = req.headers.get("content-type") || "";

    if (contentType.includes("multipart/form-data")) {
      const formData = await req.formData();
      name       = (formData.get("name")       as string) || "";
      email      = (formData.get("email")      as string) || "";
      role       = (formData.get("role")       as string) || "";
      experience = (formData.get("experience") as string) || "";
      skills     = (formData.get("skills")     as string) || "";

      const resumeEntry = formData.get("resume");
      if (resumeEntry && typeof resumeEntry !== "string") {
        const file = resumeEntry as File;
        const arrayBuffer = await file.arrayBuffer();
        resumeBuffer   = Buffer.from(arrayBuffer);
        resumeFilename = file.name;
        resumeMimeType = file.type;
      }
    } else {
      const body: ApplicationData = await req.json();
      ({ name, email, role, experience, skills } = body);
    }

    // email is optional — fall back to the configured HR inbox
    if (!email) {
      email = process.env.GMAIL_USER || "";
    }

    if (!name || !role || !experience || !skills) {
      return NextResponse.json({ error: "All fields are required" }, { status: 400 });
    }

    // Check required env vars with specific error messages
    if (!process.env.OPENROUTER_API_KEY) {
      console.error("❌ OPENROUTER_API_KEY not set");
      return NextResponse.json(
        { error: "Server configuration error: OPENROUTER_API_KEY missing" },
        { status: 500 }
      );
    }
    if (!process.env.GMAIL_USER || !process.env.GMAIL_APP_PASSWORD) {
      console.error("❌ Gmail credentials not set");
      return NextResponse.json(
        { error: "Server configuration error: Gmail credentials missing" },
        { status: 500 }
      );
    }
    if (!process.env.GITHUB_TOKEN) {
      console.error("❌ GITHUB_TOKEN not set");
      return NextResponse.json(
        { error: "Server configuration error: GITHUB_TOKEN missing" },
        { status: 500 }
      );
    }

    // No webhook secret check — open for all submissions

    // Extract text from CV so the AI can personalise the task
    let resumeText = "";
    if (resumeBuffer && resumeMimeType) {
      console.log("📄 Extracting text from CV...");
      resumeText = await extractResumeText(resumeBuffer, resumeMimeType);
      if (resumeText) console.log(`✅ CV text extracted (${resumeText.length} chars)`);
    }

    const applicationData: ApplicationData = {
      name, email, role, experience, skills,
      resumeBuffer, resumeFilename, resumeMimeType, resumeText,
    };

    console.log(`\n=== New candidate received ===`);
    console.log(`Name: ${name}`);
    console.log(`Role: ${role}`);
    console.log(`Experience: ${experience}`);
    console.log(`Skills: ${skills}`);
    console.log(`Resume: ${resumeFilename ?? "not provided"}`);

    // ── Basic validation — block obvious gibberish/spam ──────────────────
    const roleClean   = role.trim().toLowerCase();
    const skillsClean = skills.trim().toLowerCase();

    // Only reject if BOTH: no vowels AND no recognisable tech keyword
    const hasVowel    = (s: string) => /[aeiou]/i.test(s);
    const hasTechWord = (s: string) =>
      /react|node|python|java|php|ruby|swift|kotlin|flutter|angular|vue|next|express|django|spring|sql|css|html|js|ts|aws|gcp|azure|docker|git|api|ui|ux|qa|dev|ops|ml|ai|data|cloud|mobile|backend|frontend|full|stack|software|engineer|developer|designer|manager|analyst|tester|automation|security|cyber|net|c\+\+|golang|rust|scala|figma|sketch|adobe|product/i.test(s);

    // Gibberish = very short AND no tech word, OR pure symbols with no alphanumeric
    const isGibberish = (s: string) =>
      (s.length < 2 && !hasTechWord(s)) ||
      (!hasVowel(s) && !hasTechWord(s) && s.length > 1) ||
      /^[^a-z0-9\s\.\+\#\/\-]+$/i.test(s);

    if (isGibberish(roleClean)) {
      return NextResponse.json(
        { error: "Please enter a valid professional role (e.g. React Developer, UI/UX Designer)." },
        { status: 422 }
      );
    }
    if (isGibberish(skillsClean)) {
      return NextResponse.json(
        { error: "Please enter valid skills (e.g. React, Node.js, Python, Figma)." },
        { status: 422 }
      );
    }

    // ── AI Validation — spam/fake candidate detection ────────────────────
    // Fail-open: only reject if AI is confident AND the role/skills also look suspicious
    console.log("🔍 Validating candidate with AI...");
    const validation = await validateCandidate(applicationData);
    if (!validation.valid) {
      // Double-check: if role and skills have recognisable tech words, allow through anyway
      const roleHasTech  = hasTechWord(roleClean);
      const skillsHasTech = hasTechWord(skillsClean);
      if (roleHasTech || skillsHasTech) {
        console.warn("⚠️ AI rejected but role/skills look valid — allowing through");
      } else {
        console.warn(`❌ Candidate rejected: ${validation.error}`);
        return NextResponse.json({ error: validation.error }, { status: 400 });
      }
    } else {
      console.log(`✅ Candidate valid — category: ${validation.category}, seniority: ${validation.detected_seniority}`);
    }

    console.log("🤖 Generating task with OpenRouter AI...");
    const task = await generateTask(applicationData);
    console.log("Task generated:", task.title);

    console.log("🐙 Creating GitHub repo for candidate...");
    let repoUrl   = "";
    let repoOwner = "";
    let repoName  = "";
    try {
      const repoData = await createCandidateRepo(name, task);
      repoUrl   = repoData.repoUrl;
      repoOwner = repoData.repoOwner;
      repoName  = repoData.repoName;
      console.log("✅ Repo created:", repoUrl);
    } catch (repoErr) {
      console.error("❌ GitHub repo creation failed:", repoErr);
      return NextResponse.json(
        { error: `GitHub repo creation failed: ${repoErr instanceof Error ? repoErr.message : String(repoErr)}` },
        { status: 500 }
      );
    }

    console.log(`📧 Sending email to ${email}...`);
    await sendEmail(applicationData, task, repoUrl);
    console.log("✅ Email sent successfully.");

    // Save to in-memory store
    store.add({
      name,
      email,
      role,
      experience,
      skills,
      resumeFilename,
      taskTitle: task.title,
      githubRepo: repoUrl,
      repoOwner,
      repoName,
    });

    return NextResponse.json({
      success: true,
      message: "Task generated and emailed successfully",
      task_title: task.title,
    });

  } catch (error: unknown) {
    let errorMessage = "Internal server error";
    if (error instanceof Error) {
      errorMessage = error.message;
    } else if (typeof error === "string") {
      errorMessage = error;
    }
    console.error("❌ Error:", error);
    return NextResponse.json({ error: errorMessage }, { status: 500 });
  }
}
